### ISSUE TITLE
Extrange behavior reading shapefile

### ISSUE THREAD

**Issue by mainakae** [rgeo/rgeo-shapefile#7]
Hello Daniel, and thanks for sharing such a great library.

I've been using your library to import shapefiles to postgis in various different ways along the last year, but I've come to find a really extrange behavior this last week. Can't tell if it happened before, but I recently updated all my gems, so it's happening in my ruby 1.9.3p0 installation in windows, with rgeo version 0.3.20

``` ruby
shp = RGeo::Shapefile::Reader.open("C:/temporal/cartociudad_201308/CARTOCIUDAD_CALLEJERO_ASTURIAS/CODIGO_POSTAL.shp", {:srid=>4258, :assume_inner_follows_outer=>true})
shp[154]
shp[154]
```

I cannot get GEOS to work with my rgeo installation (neither in windows nor ubuntu), thus I have to add the :assumer_inner_follows_outer=>true. Anyway, the execution of the last two lines should give identical results: not the case!

```
irb(main):015:0> shp[154]
NoMethodError: undefined method `num_points' for nil:NilClass
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rgeo-0.3.20/lib/rgeo/cartesian/analysis.rb:59:in `ring_direction'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rgeo-shapefile-0.2.3/lib/rgeo/shapefile/reader.rb:639:in `block in _rea
d_polygon'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rgeo-shapefile-0.2.3/lib/rgeo/shapefile/reader.rb:638:in `map!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rgeo-shapefile-0.2.3/lib/rgeo/shapefile/reader.rb:638:in `_read_polygon
'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rgeo-shapefile-0.2.3/lib/rgeo/shapefile/reader.rb:453:in `_read_next_re
cord'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rgeo-shapefile-0.2.3/lib/rgeo/shapefile/reader.rb:397:in `next'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rgeo-shapefile-0.2.3/lib/rgeo/shapefile/reader.rb:440:in `get'
        from (irb):15
        from C:/Ruby193/bin/irb:12:in `<main>'
irb(main):016:0> shp[154]
=> #<RGeo::Shapefile::Reader::Record:0x3f418b0 @index=154, @geometry=#<RGeo::Cartesian::MultiPolygonImpl:0x1fa14d4 "MULT
IPOLYGON (((-5.74558045499992 43.3348152250001, -5.75713214699994 43.3214060830001, -5.757132305999959 43.32140603500009
5, -5.75700106199992 43.322075668000096, -5.75699589699991 43.3221020220001, -5.75734621599992 43.323030004000096, -5.75
834892899991 43.3242033540001, -5.7583528369999595 43.324833551, -5.75848624699995 43.3250554100001, -5.75852184699994 4
3.32529765, -5.75798442899992 43.3259589250001, -5.75779161599991 43.326602865, -5.757831402999949 43.32884391, -5.75776
480599995 43.3290076070001, -5.75759437799991 43.3290566950001, -5.756218712999949 43.3297291860001, -5.75549159999991 4
3.330286984000104, -5.754939349999919 43.3308945510001, -5.75484109299992 43.331176035999995, -5.755288529999921 43.3317
955360001, -5.75533632499992 43.3323076140001, -5.75526719499993 43.332687449, -5.7551272529999595 43.3334111340001, -5.
75487002399996 43.333723481, -5.753288337999949 43.335571394999995, -5.75056985199996 43.3387432430001, -5.7455804549999
2 43.3348152250001)))">, @attributes={"ID_CP"=>330310000008.0, "COD_POSTAL"=>"33929", "ALTA_DB"=>Mon, 06 Aug 2012}>
irb(main):017:0>
```

And as it goes on alternating exceptions and actual results when trying to retrieve that one row.

**Comment by teeparham** [comment]
Fixed by #18
